version: '3'

services:
  notifier:
    image: "ghcr.io/4350pchris/gh-issue-notifier"
    build: .
    environment:
      SHOUTRRR_URL: "${SHOUTRRR_URL}"
      INTERVAL: "${INTERVAL}"
    ports: 
      - "8080:8080"
    volumes:
      - ./patterns.yaml:/patterns.yaml
      - ./issues.txt:/issues.txt
