version: '3'

services:
  notifier:
    image: "ghcr.io/4350pchris/gh-issue-notifier"
    build: .
    environment:
      SHOUTRRR_URL: "${SHOUTRRR_URL}"
      INTERVAL: "${INTERVAL}"
      WATCH_PATTERNS: "${WATCH_PATTERNS}"
    volumes:
      - ./issues.txt:/issues.txt
